### ISSUE TITLE
Fix failing test

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tracking-protection-issues#13]
Oops. I merged too eagerly. :)

```
🐓 pipenv run nose2
Loading .env environment variables...
E....
======================================================================
ERROR: test_create_issue (tests.test_endpoints.TestEndpoints)
Test new issue endpoint.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 3, in wrapper
  File "/Users/miket/dev/tracking-protection-issues/tests/test_endpoints.py", line 60, in test_create_issue
    '/new', data=dict(title='hi', body='dude')
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/werkzeug/test.py", line 1039, in post
    return self.open(*args, **kw)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/flask/testing.py", line 200, in open
    follow_redirects=follow_redirects
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/werkzeug/test.py", line 993, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/werkzeug/test.py", line 884, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/miket/dev/tracking-protection-issues/app/endpoints/issues.py", line 45, in new_issue
    rv = create_issue(body, title, labels)
  File "/Users/miket/dev/tracking-protection-issues/app/helpers.py", line 40, in create_issue
    rv = find_issue(title)
  File "/Users/miket/dev/tracking-protection-issues/app/helpers.py", line 25, in find_issue
    return requests.get(uri, headers=HEADERS)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/responses.py", line 600, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/Users/miket/.local/share/virtualenvs/tracking-protection-issues-MGe0Zt1T/lib/python2.7/site-packages/responses.py", line 575, in _on_request
    raise response
ConnectionError: Connection refused: GET https://api.github.com/search/issues?q='hi'+type:issue+repo:test/test-repo+created:%3E=2019-10-19&sort=created&order=desc
```
Seems like an instance of https://github.com/getsentry/responses/issues/148, perhaps, since before we didn't have any query strings. Or we need to tell responses to mock out the request to this API endpoint, rather than actually hit google.

**Comment by miketaylr** [comment]
Regression from https://github.com/mozilla/tracking-protection-issues/pull/12, but it just affects the tests passing.
